account/urls.py
from django.conf.urls import url
from django.conf import settings
from django.contrib.auth import views as auth_views

from . import views

urlpatterns = [
    #url(r'^login/$', views.user_login, name='user_login'), #自定义的登录
    url(r'^login/$', auth_views.login, name='user_login'),  #django内置的登录
    url(r'^new-login/$', auth_views.login, {"template_name": "account/login.html", }),
    url(r'^logout/$', auth_views.logout, {'template_name': "account/logout.html"}, name='user_logout'),
    url(r'^register/$', views.register, name="user_register"),
    url(r'^password-change/$', auth_views.password_change, {"post_change_redirect": "/account/password-change-done"},
        name='password_change'),
    url(r'^password-change-done/$', auth_views.password_change_done, name='password_change_done'),

    url(r'password-reset/$', auth_views.password_reset, {"template_name": "account/password_reset_form.html",
                                                         "email_template_name": "account/password_reset_email.html",
                                                         "subject_template_name": "account/password_reset_subject.html",
                                                         "post_reset_redirect": "/account/password-reset-done"},
        name='password_reset'),
    url(r'^password-reset-done/$', auth_views.password_reset_done,
        {"template_name": "account/password_reset_done.html"}, name="password_reset_done"),
    url(r'^password-reset-confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/$', auth_views.password_reset_confirm,
        {"template_name": "account/password_reset_confirm.html",
         "post_reset_redirect": "/account/password-reset-complete"}, name="password_reset_confirm"),
    url(r'^password-reset-complete/$', auth_views.password_reset_complete,
        {"template_name": "account/password_reset_complete.html"}, name="password_reset_complete"),

]

blog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.blog_title, name='blog_title'),
    url(r'^(?P<article_id>\d+)/$', views.blog_article, name='blog_article')
]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls', namespace='blog', app_name='blog')),
    url(r'^account/', include('account.urls', namespace='account', app_name='account')),

]

account/models.py
from django.db import models
from django.contrib.auth.models import User

class UserProfile(models.Model):
    user = models.OneToOneField(User, unique=True)
    birth = models.DateField(blank=True, null=True)
    phone = models.CharField(max_length=20, null=True)

    def __str__(self):
        return 'user {}'.format(self.user.username)

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

class BlogArticles(models.Model):
    title = models.CharField(max_length=300)
    author = models.ForeignKey(User, related_name="blog_post")
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)

    class Meta:
        ordering = ("-publish",)

    def __str__(self):
        return self.title

account/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import UserProfile


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


class RegistrationForm(forms.ModelForm):
    password = forms.CharField(label="Password", widget=forms.PasswordInput)
    password2 = forms.CharField(label="Confirm Password", widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ("username", "email")

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError("passwords do not match.")
        return cd['password2']


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ("phone", "birth")

account/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth import authenticate, login
from .forms import LoginForm,  RegistrationForm, UserProfileForm


def user_login(request):
    if request.method == "POST":
        login_form = LoginForm(request.POST)
        if login_form.is_valid():
            cd = login_form.cleaned_data
            user = authenticate(username=cd['username'], password=cd['password'])

            if user:
                login(request, user)
                return HttpResponse("welcome you. you have been authenticated successfully")
            else:
                return HttpResponse("sorry, your username or password is not right.")

        else:
            return HttpResponse("invalid login")

    if request.method == "GET":
        login_form = LoginForm()
        return render(request, "account/login.html", {"form": login_form})


def register(request):
    if request.method == "POST":
        user_form = RegistrationForm(request.POST)
        userprofile_form = UserProfileForm(request.POST)
        if user_form.is_valid() and userprofile_form.is_valid():
            new_user = user_form.save(commit=False)
            new_user.set_password(user_form.cleaned_data['password'])
            new_user.save()
            new_profile = userprofile_form.save(commit=False)
            new_profile.user = new_user
            new_profile.save()
            return HttpResponse('successfully')
        else:
            return HttpResponse("sorry, you can not register.")
    else:
        user_form = RegistrationForm()
        userprofile_form = UserProfileForm()
        return render(request, "account/register.html", {"form": user_form, "profile": userprofile_form})

blog/views.py
from django.shortcuts import render, get_object_or_404

from .models import BlogArticles


def blog_title(request):
    blogs = BlogArticles.objects.all()
    return render(request, "blog/titles.html", {"blogs": blogs})

def blog_article(request, article_id):
    #article = BlogArticles.objects.get(id=article_id)
    article = get_object_or_404(BlogArticles, id=article_id)
    pub = article.publish
    return render(request, 'blog/content.html', {"article": article, "publish": pub})

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-theme.min.css' %}">
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries。 WARNING: Respond.js doesn't work if you view the page via file://-->
    <!--[if lt IE 9]>
      <script src="{% static 'js/html5shiv.min.js' %}"></script>
      <script src="{% static 'js/respond.min.js' %}"></script>
    <![endif]-->
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    {% include "header.html" %}
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
    {% include "footer.html" %}
    {% block javascript %}{% endblock %}
    <script src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

templates/blog/content.html
{% extends "base.html" %}

{% block title %}blog article{% endblock %}

{% block content %}
    <div class="row text-center vertical-middle-sm">
        <h1>{{ article.title }}</h1>
    </div>
    <div class="row">
       <div class="col-xs-12 col-md-8">
            <p class="text-center">
                <span>
                    {{ article.author.username }}
                </span>
                <span style="margin-left:20px">
                    {{ publish }}
                </span>
            </p>
           <div>
               {{ article.body }}
           </div>
       </div>
       <div class="col-xs-6 col-md-4">
           <h2>广告</h2>
           <p>跟老齐学： www.itdiffer.com</p>
           <img width="200px" src="http://www.itdiffer.com/files/system/2017/01-17/112342e6f9b6271601.png?7.0.1">
       </div>
    </div>
{% endblock %}

templates/blog/titles.html
{% extends "base.html" %}

{% block title %}blog titles{% endblock %}

{% block content %}
    <div class="row text-center vertical-middle-sm">
        <h1>我的博客</h1>
    </div>
    <div class="row">
       <div class="col-xs-12 col-md-8">
           <ul>
               {% for blog in blogs %}
                   <li>
                       <a href="{{ blog.id }}">{{ blog.title }}</a>
                   </li>
               {% endfor %}
           </ul>
       </div>
       <div class="col-xs-6 col-md-4">
           <h2>广告</h2>
           <p>跟老齐学： www.itdiffer.com</p>
           <img width="200px" src="http://www.itdiffer.com/files/system/2017/01-17/112342e6f9b6271601.png?7.0.1">
       </div>
    </div>
{% endblock %}

templates/footer.html
<div class="container">
    <hr>
    <p class="text-center">copy right www.itdiffer.com</p>
</div>

templates/header.html
{% load staticfiles %}
<div class="container">
    <nav class="navbar nav-default" role="navigation">
        <div class="navbar-header">
            <a class="navbar-brand" href="http://www.itdiffer.com"><img src="{% static '/images/logo.png' %}"
                                                                        width="100px"></a>
        </div>
        <div>
            <ul class="nav navbar-nav" role="navigation">
                <li>
                    <a href="{% url 'blog:blog_title' %}">BLOG</a>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right" style="margin-right:10px">
                {% if user.is_authenticated %}
                    <li>
                        <div class="dropdown" style="margin-top:8px">
                            <button class="btn btn-default dropdown-toggle" type="button" id="dropdrownMenu" data-toggle
                                    ='dropdown'>
                                {{ user.username }}
                                <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu">
                                <li>
                                    <a href="{% url 'account:password_change' %}">修改密码</a>
                                </li>
                            </ul>
                        </div>
                    </li>
                    <li><a href="{% url 'account:user_logout' %}">Logout</a></li>
                {% else %}
                    <li><a href="{% url 'account:user_login' %}">LOGIN</a></li>
                {%  endif %}

            </ul>
        </div>
    </nav>
</div>